### PR TITLE
fix: pick default GH refs API endpoint based on package version

### PR DESCRIPTION
**Pull request by arbrandes**
Picking up where https://github.com/overhangio/tutor-mfe/pull/131 left off.

### CODE REVIEW

**Comment by arbrandes** [comment]
@regisb, basically just a conversation starter.  I'm not sure this is the best way to handle this.  (But it could be. 🤷🏼‍♂️)

**Review by regisb — APPROVED** [review]
I think this should be good enough for now. We can probably merge this as-is and then work on an improvement later.

**Comment by arbrandes** [comment]
Tested and it's working, so going ahead and merging.

I'm also going to revert the previous nightly fix, and also add the "nightly" version suffix.

**Comment by regisb** [comment]
With hindsight, this change is really super useful, especially in CI.

**Pull request merged**
