### PR TITLE
Learning MFE issue with certificates

### PR DESCRIPTION
**Pull request by CodeWithEmad**
as mentioned [here](https://github.com/overhangio/tutor-mfe/issues/45), after migrating to MFEs, if PersistentGradesEnabledFlag is not enabled, after the certification creation request, an error will happen and it makes the pod restart.
this fix creates a PersistentGradesEnabledFlag record once if the user enabled the Learning MFE.

### CODE REVIEW

**Comment by regisb** [comment]
Thanks for this PR @CodeWithEmad. To be honest I incorrectly believed that persistent grades were enabled by default in Tutor. I think that this is an important feature that should be enabled for everyone. Since it's a potentially impactful change, I would like to introduce it in Nutmeg, our next release.

In the meantime, you are right that we should be fixing this in Maple. I agree that persistent grades should be enabled by default for everyone who is using the learning MFE. However, I'd like to avoid the creation of a configuration model. Instead, I'd like to suggest that you add the following lines to the lms common settings template:

    FEATURES["PERSISTENT_GRADES_ENABLED_FOR_ALL_TESTS"] = True

In my understanding,this feature flag should have the same effect as the creation of a configuration model, but it's much easier to rollback.

**Comment by CodeWithEmad** [comment]
okay, that's a better solution. I'll open a PR in the tutor project

**Comment by CodeWithEmad** [comment]
@regisb you can take a look at [here](https://github.com/overhangio/tutor/pull/655)

**Comment by regisb** [comment]
Hey @CodeWithEmad, I'm sorry about the confusion. I meant to add the feature flag here in the tutor-mfe setting, as a plugin patch, not in the Tutor core configuration, such that it is enabled only for users who run the mfe plugin. I'll reopen this PR and you can close https://github.com/overhangio/tutor/pull/655

**Comment by CodeWithEmad** [comment]
oops. my bad. I thought you were talking about the tutor core. 
sure, I'll take care of it.
just to be sure; adding `FEATURES["PERSISTENT_GRADES_ENABLED_FOR_ALL_TESTS"] = True` to both `openedx-lms-development-settings` and `openedx-lms-production-settings` sufficed?
don't we have a changelog to see what has been added to the project in each release?

**Comment by regisb** [comment]
>  just to be sure; adding FEATURES["PERSISTENT_GRADES_ENABLED_FOR_ALL_TESTS"] = True to both openedx-lms-development-settings and openedx-lms-production-settings sufficed?

Actually, you can add this feature flag both to dev and prod by creating a single patch "openedx-lms-common-settings" https://docs.tutor.overhang.io/reference/patches.html#openedx-lms-common-settings

>  don't we have a changelog to see what has been added to the project in each release?

No we don't... yet. But this will change very soon, I swear!

**Comment by CodeWithEmad** [comment]
> No we don't... yet. But this will change very soon, I swear!

😆 😆 😆  no worries. 

> Actually, you can add this feature flag both to dev and prod by creating a single patch "openedx-lms-common-settings"
Done. please take a look

**Review by regisb — APPROVED** [review]

**Review by regisb — APPROVED** [review]

**Pull request merged**
