### PR TITLE
imagePullPolicy value must start with Capital letters

### PR DESCRIPTION
**Pull request by CodeWithEmad**

### CODE REVIEW

**Review by regisb — APPROVED** [review]
This looks good! Please add a "Close #4" line in the commit message and we'll merge it right away.

**Comment by regisb** [comment]
This ready for merging @CodeWithEmad @EmadEhsanrad. Can you please just squash your commits?

**Comment by CodeWithEmad** [comment]
it`s done.

**Comment by CodeWithEmad** [comment]
@regisb is it possible to merge this.
I really need it for my work.
thank you

**Review by regisb — APPROVED** [review]

**Comment by regisb** [comment]
Thanks for your pr @CodeWithEmad! This fix is included in v12.0.1, which was released a few seconds ago.

**Pull request merged**
