### PR TITLE
Add INFO_EMAIL and PASSWORD_RESET_SUPPORT_LINK

### LINKED ISSUE #139: Bug: Required MFE-Auth variables are not defined which breaks the UI
Both `INFO_EMAIL` and `PASSWORD_RESET_SUPPORT_LINK` are missing, and possible others from the https://github.com/openedx/frontend-app-authn documentation. 

## Missing `INFO_EMAIL`

Steps to reproduce missing `INFO_EMAIL`
1. Go to https://apps.demo.openedx.overhang.io/authn/reset?next=%2F
2. See sentence that doesn't complete, "support at"
image

If `MFE_CONFIG["INFO_EMAIL"] = "{{ CONTACT_EMAIL }}"` set via a plugin you get the following 
image

## Missing `PASSWORD_RESET_SUPPORT_LINK`

Without `PASSWORD_RESET_SUPPORT_LINK` the href is not generated correctly. 

image

When `MFE_CONFIG["PASSWORD_RESET_SUPPORT_LINK"] = "mailto:{{ CONTACT_EMAIL }}"` set via a plugin you get the following:

image

## Proposed Solution
Add the following to https://github.com/overhangio/tutor-mfe/blob/8522ab6adf149d27e6aeaed567795857af1c0647/tutormfe/patches/openedx-lms-production-settings#L3C1-L3C11

```
INFO_EMAIL = "{{ CONTACT_EMAIL }}
PASSWORD_RESET_SUPPORT_LINK = "mailto:{{ CONTACT_EMAIL }}"
```

@regisb if this makes sense, I can create a PR for it.

### PR DESCRIPTION
**Pull request by misilot**
These two variables are used to generate links in the standard MFE Auth Site Template for resetting passwords.

Fixes #139

I don't currently have anyway to test with `tutor-dev` but I did apply this on our test instance running `tutor local` as a patch.

### CODE REVIEW

**Comment by regisb** [comment]
Right. I mentioned the `dev` environment because you will almost certainly  have to implement the "openedx-lms-development-settings" patch, in addition to the production patch.

**Comment by misilot** [comment]
Thanks @regisb. I am willing to try and get it running. 

What would be the most straightforward way to test my branch? I assume I will need to build tutor-mfe, but reading through the README in this repo, and the Tutor docs, I am not seeing if there is a way specify the github repo/branch as the source for the mfe.

**Comment by misilot** [comment]
After changing to my tutor-mfe branch

image

After putting in a test email, the href is also populated (bottom left of image)
image

These changes did not require any additional patch to be applied to use the default CONTACT_EMAIL which is generated during launch.

**Review by regisb — CHANGES_REQUESTED** [review]
Looking good! Can you please add an entry to the changelog with `scriv create`?

**Comment by misilot** [comment]
@regisb done

**Review by regisb — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
