### PR TITLE
fix: enable meilisearch in MFE config

### PR DESCRIPTION
**Pull request by pomegranited**
Depends on https://github.com/overhangio/tutor/pull/1141

Part of: https://github.com/openedx/modular-learning/issues/236

### CODE REVIEW

**Review by DawoudSheraz — APPROVED** [review]

**Comment by Faraz32123** [comment]
why not adding this setting to `openedx-lms-common-settings` instead of adding in both dev and prod patches?

**Comment by regisb** [comment]
It's true we could probably move the shared configurations to "openedx-lms-common-settings". I'd say it's slightly beyond the scope of this PR, and we risk running into rebase conflicts if we make other changes in the master branch until Sumac is released. But I'll agree with whatever ya'll decide.

**Comment by pomegranited** [comment]
@Faraz32123 Let me know what you'd like me to do? I'm just a user of this repo, not an expert like y'all :)

**Comment by Faraz32123** [comment]
> @Faraz32123 Let me know what you'd like me to do? I'm just a user of this repo, not an expert like y'all :)

@pomegranited all good from your side, Thanks. I think, we can merge this PR.
We'll refactor the patches in a separate PR.

**Review by DawoudSheraz — COMMENTED** [review]
One thing: please add a changelog entry and it should be ready to merge.

**Review by regisb — APPROVED** [review]

**Comment by DawoudSheraz** [comment]
I am going to merge this PR, we can add the changelog in a follow-up PR. Since Sumac sandbox is going to be re-created on Monday morning, it is essential to have this change in place as tutor core PR for meilisearch has been merged.

**Pull request merged**
